// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY25qLJJjaCOc8thFNf10Yo7fhCspurE8',
    appId: '1:587869616564:web:8d2a05f72a2da253ba9ae1',
    messagingSenderId: '587869616564',
    projectId: 'wgym-app',
    authDomain: 'wgym-app.firebaseapp.com',
    storageBucket: 'wgym-app.firebasestorage.app',
    measurementId: 'G-X5NGPP17TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUSi6UaY50SF6HvzEj-0S9HmrtmNba0Ts',
    appId: '1:587869616564:android:e6ce1b4a5497b863ba9ae1',
    messagingSenderId: '587869616564',
    projectId: 'wgym-app',
    storageBucket: 'wgym-app.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY25qLJJjaCOc8thFNf10Yo7fhCspurE8',
    appId: '1:587869616564:web:7a905a9a9375928dba9ae1',
    messagingSenderId: '587869616564',
    projectId: 'wgym-app',
    authDomain: 'wgym-app.firebaseapp.com',
    storageBucket: 'wgym-app.firebasestorage.app',
    measurementId: 'G-10BCTC9SNK',
  );
}
